# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wordgame.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ewordgame.proto\x12\x06protos\"\x10\n\x0eWelcomeRequest\"\x1f\n\x0cWelcomeReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0bModeRequest\x12\x10\n\x08gameType\x18\x01 \x01(\t\".\n\tModeReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08typeMode\x18\x02 \x01(\x05\"\x1f\n\rLetterRequest\x12\x0e\n\x06letter\x18\x01 \x01(\t\"5\n\x0bLetterReply\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x14\n\x0cgameFinished\x18\x02 \x01(\x08\"\x1b\n\x0bTurnRequest\x12\x0c\n\x04user\x18\x01 \x01(\x05\"\x1d\n\tTurnReply\x12\x10\n\x08isMyTurn\x18\x01 \x01(\x08\"\x17\n\x15TeamMateAnswerRequest\"T\n\x13TeamMateAnswerReply\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x14\n\x0cgameFinished\x18\x02 \x01(\x08\x12\x15\n\rfinalSentence\x18\x03 \x01(\t\" \n\x0e\x43heckIDRequest\x12\x0e\n\x06gameID\x18\x01 \x01(\t\"!\n\x0c\x43heckIDReply\x12\x11\n\tcorrectID\x18\x01 \x01(\x08\"\x11\n\x0fGameCodeRequest\"!\n\rGameCodeReply\x12\x10\n\x08GameCode\x18\x01 \x01(\t2\xd0\x03\n\x08WordGame\x12\x41\n\x0f\x46irstConnection\x12\x16.protos.WelcomeRequest\x1a\x14.protos.WelcomeReply\"\x00\x12\x36\n\nSelectMode\x12\x13.protos.ModeRequest\x1a\x11.protos.ModeReply\"\x00\x12;\n\x0bGuessLetter\x12\x15.protos.LetterRequest\x1a\x13.protos.LetterReply\"\x00\x12\x35\n\tCheckTurn\x12\x13.protos.TurnRequest\x1a\x11.protos.TurnReply\"\x00\x12S\n\x13\x43heckTeamMateAnswer\x12\x1d.protos.TeamMateAnswerRequest\x1a\x1b.protos.TeamMateAnswerReply\"\x00\x12=\n\x0b\x43heckGameID\x12\x16.protos.CheckIDRequest\x1a\x14.protos.CheckIDReply\"\x00\x12\x41\n\rGetMyGameCode\x12\x17.protos.GameCodeRequest\x1a\x15.protos.GameCodeReply\"\x00\x42\x17\x42\rWordGameProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_WELCOMEREQUEST = DESCRIPTOR.message_types_by_name['WelcomeRequest']
_WELCOMEREPLY = DESCRIPTOR.message_types_by_name['WelcomeReply']
_MODEREQUEST = DESCRIPTOR.message_types_by_name['ModeRequest']
_MODEREPLY = DESCRIPTOR.message_types_by_name['ModeReply']
_LETTERREQUEST = DESCRIPTOR.message_types_by_name['LetterRequest']
_LETTERREPLY = DESCRIPTOR.message_types_by_name['LetterReply']
_TURNREQUEST = DESCRIPTOR.message_types_by_name['TurnRequest']
_TURNREPLY = DESCRIPTOR.message_types_by_name['TurnReply']
_TEAMMATEANSWERREQUEST = DESCRIPTOR.message_types_by_name['TeamMateAnswerRequest']
_TEAMMATEANSWERREPLY = DESCRIPTOR.message_types_by_name['TeamMateAnswerReply']
_CHECKIDREQUEST = DESCRIPTOR.message_types_by_name['CheckIDRequest']
_CHECKIDREPLY = DESCRIPTOR.message_types_by_name['CheckIDReply']
_GAMECODEREQUEST = DESCRIPTOR.message_types_by_name['GameCodeRequest']
_GAMECODEREPLY = DESCRIPTOR.message_types_by_name['GameCodeReply']
WelcomeRequest = _reflection.GeneratedProtocolMessageType('WelcomeRequest', (_message.Message,), {
  'DESCRIPTOR' : _WELCOMEREQUEST,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.WelcomeRequest)
  })
_sym_db.RegisterMessage(WelcomeRequest)

WelcomeReply = _reflection.GeneratedProtocolMessageType('WelcomeReply', (_message.Message,), {
  'DESCRIPTOR' : _WELCOMEREPLY,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.WelcomeReply)
  })
_sym_db.RegisterMessage(WelcomeReply)

ModeRequest = _reflection.GeneratedProtocolMessageType('ModeRequest', (_message.Message,), {
  'DESCRIPTOR' : _MODEREQUEST,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.ModeRequest)
  })
_sym_db.RegisterMessage(ModeRequest)

ModeReply = _reflection.GeneratedProtocolMessageType('ModeReply', (_message.Message,), {
  'DESCRIPTOR' : _MODEREPLY,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.ModeReply)
  })
_sym_db.RegisterMessage(ModeReply)

LetterRequest = _reflection.GeneratedProtocolMessageType('LetterRequest', (_message.Message,), {
  'DESCRIPTOR' : _LETTERREQUEST,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.LetterRequest)
  })
_sym_db.RegisterMessage(LetterRequest)

LetterReply = _reflection.GeneratedProtocolMessageType('LetterReply', (_message.Message,), {
  'DESCRIPTOR' : _LETTERREPLY,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.LetterReply)
  })
_sym_db.RegisterMessage(LetterReply)

TurnRequest = _reflection.GeneratedProtocolMessageType('TurnRequest', (_message.Message,), {
  'DESCRIPTOR' : _TURNREQUEST,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.TurnRequest)
  })
_sym_db.RegisterMessage(TurnRequest)

TurnReply = _reflection.GeneratedProtocolMessageType('TurnReply', (_message.Message,), {
  'DESCRIPTOR' : _TURNREPLY,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.TurnReply)
  })
_sym_db.RegisterMessage(TurnReply)

TeamMateAnswerRequest = _reflection.GeneratedProtocolMessageType('TeamMateAnswerRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEAMMATEANSWERREQUEST,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.TeamMateAnswerRequest)
  })
_sym_db.RegisterMessage(TeamMateAnswerRequest)

TeamMateAnswerReply = _reflection.GeneratedProtocolMessageType('TeamMateAnswerReply', (_message.Message,), {
  'DESCRIPTOR' : _TEAMMATEANSWERREPLY,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.TeamMateAnswerReply)
  })
_sym_db.RegisterMessage(TeamMateAnswerReply)

CheckIDRequest = _reflection.GeneratedProtocolMessageType('CheckIDRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKIDREQUEST,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.CheckIDRequest)
  })
_sym_db.RegisterMessage(CheckIDRequest)

CheckIDReply = _reflection.GeneratedProtocolMessageType('CheckIDReply', (_message.Message,), {
  'DESCRIPTOR' : _CHECKIDREPLY,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.CheckIDReply)
  })
_sym_db.RegisterMessage(CheckIDReply)

GameCodeRequest = _reflection.GeneratedProtocolMessageType('GameCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMECODEREQUEST,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.GameCodeRequest)
  })
_sym_db.RegisterMessage(GameCodeRequest)

GameCodeReply = _reflection.GeneratedProtocolMessageType('GameCodeReply', (_message.Message,), {
  'DESCRIPTOR' : _GAMECODEREPLY,
  '__module__' : 'wordgame_pb2'
  # @@protoc_insertion_point(class_scope:protos.GameCodeReply)
  })
_sym_db.RegisterMessage(GameCodeReply)

_WORDGAME = DESCRIPTOR.services_by_name['WordGame']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\rWordGameProtoP\001\242\002\003HLW'
  _WELCOMEREQUEST._serialized_start=26
  _WELCOMEREQUEST._serialized_end=42
  _WELCOMEREPLY._serialized_start=44
  _WELCOMEREPLY._serialized_end=75
  _MODEREQUEST._serialized_start=77
  _MODEREQUEST._serialized_end=108
  _MODEREPLY._serialized_start=110
  _MODEREPLY._serialized_end=156
  _LETTERREQUEST._serialized_start=158
  _LETTERREQUEST._serialized_end=189
  _LETTERREPLY._serialized_start=191
  _LETTERREPLY._serialized_end=244
  _TURNREQUEST._serialized_start=246
  _TURNREQUEST._serialized_end=273
  _TURNREPLY._serialized_start=275
  _TURNREPLY._serialized_end=304
  _TEAMMATEANSWERREQUEST._serialized_start=306
  _TEAMMATEANSWERREQUEST._serialized_end=329
  _TEAMMATEANSWERREPLY._serialized_start=331
  _TEAMMATEANSWERREPLY._serialized_end=415
  _CHECKIDREQUEST._serialized_start=417
  _CHECKIDREQUEST._serialized_end=449
  _CHECKIDREPLY._serialized_start=451
  _CHECKIDREPLY._serialized_end=484
  _GAMECODEREQUEST._serialized_start=486
  _GAMECODEREQUEST._serialized_end=503
  _GAMECODEREPLY._serialized_start=505
  _GAMECODEREPLY._serialized_end=538
  _WORDGAME._serialized_start=541
  _WORDGAME._serialized_end=1005
# @@protoc_insertion_point(module_scope)
